### ISSUE TITLE
我知道的几个未列出的地址，望更新一下

### ISSUE THREAD

**Issue by Alvin-Liu** [foru17/front-end-collect#43]
github：
阮一峰：https://github.com/ruanyf
勾三股四：https://github.com/Jinjiang

微博：
司徒正美：http://weibo.com/jslouvre

**Comment by yoyo-git** [comment]
Thank you for your share!

在 2016-03-06 19:19:57，"alvin-liu" <notifications@github.com> 写道：


github：
阮一峰：https://github.com/ruanyf
勾三股四：https://github.com/Jinjiang

微博：
司徒正美：http://weibo.com/jslouvre

**Comment by kanlidy** [comment]
谢谢您，后面一定做更好，可能会用Python做一个收集器。


晚上更新上去
在2016年03月07日 08:45，yoyo 写道:
Thank you for your share!

在 2016-03-06 19:19:57，"alvin-liu" <notifications@github.com> 写道：


github：
阮一峰：https://github.com/ruanyf
勾三股四：https://github.com/Jinjiang

微博：
司徒正美：http://weibo.com/jslouvre
